name: Test

on: [ push ]

jobs:
  test:
    strategy:
      fail-fast: true
      matrix:
        python: [3.7.9, 3.8.10, 3.9.13]
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    name: test-${{ matrix.python }}-${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Python setup
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
          architecture: x64

      - name: Install dependencies
        run: make dependencies

      - name: Run tests
        run: nox -s "test(python='${{ matrix.python }}')"
